### ISSUE TITLE
Add class to output of `bitmap_text_matrix()` and `vector_text_matrix()`?

### ISSUE THREAD

**Issue by trevorld** [coolbutuseless/lofifonts#1]
Currently to convert your binary matrix to a `{bittermelon}` bitmap object we need to remember to vertically flip the matrix:

```r
mat <- bitmap_text_matrix("Hello", "unifont")
bm <- as_bm_bitmap(mat) |> bm_flip()
```

If `bitmap_text_matrix()` had a class name we could write a `as_bm_bitmap()` class method for it that remembers to vertically flip for us:

```r
bm <- as_bm_bitmap(mat)
```

Could then pretty print your included fonts to the terminal, etc.

**Comment by trevorld** [comment]
FYI: to convert to your three formats *from* `{bittermelon}` would be something like:

* `as.matrix(bm, first_row_is_top = TRUE)`
* https://github.com/trevorld/bittermelon/issues/78
* `as.raster(bm, native = FALSE)`

In case you'd ever want to support additional font formats in the `font` argument and use `{bittermelon}` as a back-end...

**Comment by coolbutuseless** [comment]
Thanks @trevorld 

The fuzzy goal for this package is: "Fast access to formatted passages of text with bitmap/vector fonts which can be rendered to arbitrary graphical outputs".   i.e. a text layout engine with some builtin fonts.

The "coords" output is the primary output.   The matrix and raster are just there for quick preview.

One workflow I'm considering:

1. Load a font with `{bittermelon}`
2. Convert to my internal font representation
    * get the coords for each character in the font
    * accumulate/index these coordinates into my bespoke representation
3. Adjust `bitmap_text_coords()` etc to accept this as the `font` argument.

```r
# hypothetical
font_file <- system.file("fonts/spleen/spleen-8x16.hex.gz", package = "bittermelon")
font <- read_hex(font_file)
lofi <- bm_to_lofi(font)
bitmap_text_coords("Anything goes\nhere", font = lofi)
```

So step 2 would need the feature being considered here: https://github.com/trevorld/bittermelon/issues/78

I'm happy to roll my own `bm_coords()` to access this pixel coordinate data, so no pressure to include anything in bittermelon just for me!

**Comment by trevorld** [comment]
> So step 2 would need the feature being considered here: https://github.com/trevorld/bittermelon/issues/78
>
> I'm happy to roll my own bm_coords() to access this pixel coordinate data, so no pressure to include anything in bittermelon just for me!

* I think for now you can roll out your own function.  I'll probably add an `as.data.frame()` method to `{bittermelon}` in the future but I don't plan to do this in a hurry.  I think you already have the pieces needed to straightforwardly do this conversion (let me know if don't).
* Note I think I was able to simplify your initial version here: https://github.com/trevorld/bittermelon/issues/78#issuecomment-2439678352 

```r
coords <- arrayInd(which(as.logical(bm)), dim(bm)) |> 
    as.data.frame() |> 
    stats::setNames(c("y", "x")) # Note the first column is y coordinates!
```

**Comment by coolbutuseless** [comment]
I've added a class of "lofi-matrix" to matrix output, but I'm not going to take this any further for this initial release.

**Comment by trevorld** [comment]
Thanks!  I added an `as_bm_bitmap.lofi-matrix()` method to the development version of `{bittermelon}`:

```r
lofifonts::bitmap_text_matrix("Hello", "unifont") |> 
    bittermelon::bm_print(compress = "none", fg = cli::col_none, bg = cli::bg_none)
```
```
░░░░░░░░░░░░░░░░░░░██░░░░░░██░░░░░░░░░░
░█░░░░█░░░░░░░░░░░░░█░░░░░░░█░░░░░░░░░░
░█░░░░█░░░░░░░░░░░░░█░░░░░░░█░░░░░░░░░░
░█░░░░█░░░████░░░░░░█░░░░░░░█░░░░░████░
░█░░░░█░░█░░░░█░░░░░█░░░░░░░█░░░░█░░░░█
░██████░░█░░░░█░░░░░█░░░░░░░█░░░░█░░░░█
░█░░░░█░░██████░░░░░█░░░░░░░█░░░░█░░░░█
░█░░░░█░░█░░░░░░░░░░█░░░░░░░█░░░░█░░░░█
░█░░░░█░░█░░░░░░░░░░█░░░░░░░█░░░░█░░░░█
░█░░░░█░░█░░░░█░░░░░█░░░░░░░█░░░░█░░░░█
░█░░░░█░░░████░░░░█████░░░█████░░░████░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
                             
```

**Comment by coolbutuseless** [comment]
Awesome!
